# This is a basic workflow to help you get started with Actions
name: PR User-java

# Controls when the action will run.
#on:
## Triggers the workflow on push or pull request events but only for the master branch
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'apis/user-java/**'

on: push

jobs:
  quality-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Quality
        run: |
          mvn test
