# This is a basic workflow to help you get started with Actions
name: PR USERPROFILE

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

jobs:          
  quality-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Quality
        run: |
          cd apis/userprofile
          npm i
          npm run test
      - uses: JasonEtco/create-an-issue@v2
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          project: https://github.com/GetafixIT/openhack-devops-team/projects/1
          column_name: To do
